name: Build and Publish Release

on:
  push:
    branches:
      - main  # You can change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.3  # Use the Go version you need

      - name: Build
        run: go build -v ./...

      - name: Archive the build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: ./ # Specify the path to the build output

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: ./ # Specify where to download the build output

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./  # Specify the path to the build output
          asset_name: DistributedFileStorage  # Name your asset
          asset_content_type: application/octet-stream
